// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadL4Sender returns the embedded CollectionSpec for L4Sender.
func LoadL4Sender() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_L4SenderBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load L4Sender: %w", err)
	}

	return spec, err
}

// LoadL4SenderObjects loads L4Sender and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*L4SenderObjects
//	*L4SenderPrograms
//	*L4SenderMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadL4SenderObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadL4Sender()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// L4SenderSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4SenderSpecs struct {
	L4SenderProgramSpecs
	L4SenderMapSpecs
	L4SenderVariableSpecs
}

// L4SenderProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4SenderProgramSpecs struct {
	TcpV4ConnectEnter *ebpf.ProgramSpec `ebpf:"tcp_v4_connect_enter"`
}

// L4SenderMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4SenderMapSpecs struct {
	L4Events *ebpf.MapSpec `ebpf:"l4_events"`
}

// L4SenderVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L4SenderVariableSpecs struct {
}

// L4SenderObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadL4SenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type L4SenderObjects struct {
	L4SenderPrograms
	L4SenderMaps
	L4SenderVariables
}

func (o *L4SenderObjects) Close() error {
	return _L4SenderClose(
		&o.L4SenderPrograms,
		&o.L4SenderMaps,
	)
}

// L4SenderMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadL4SenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type L4SenderMaps struct {
	L4Events *ebpf.Map `ebpf:"l4_events"`
}

func (m *L4SenderMaps) Close() error {
	return _L4SenderClose(
		m.L4Events,
	)
}

// L4SenderVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadL4SenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type L4SenderVariables struct {
}

// L4SenderPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadL4SenderObjects or ebpf.CollectionSpec.LoadAndAssign.
type L4SenderPrograms struct {
	TcpV4ConnectEnter *ebpf.Program `ebpf:"tcp_v4_connect_enter"`
}

func (p *L4SenderPrograms) Close() error {
	return _L4SenderClose(
		p.TcpV4ConnectEnter,
	)
}

func _L4SenderClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed l4sender_bpfeb.o
var _L4SenderBytes []byte
