apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"alloy-ebpf-repro"},"rules":[{"apiGroups":[""],"resources":["pods","nodes","namespaces"],"verbs":["get","list","watch"]}]}
  name: alloy-ebpf-repro
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - get
  - list
  - watch
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"prometheus-ebpf-repro"},"rules":[{"apiGroups":[""],"resources":["pods","nodes","services","endpoints"],"verbs":["get","list","watch"]}]}
  name: prometheus-ebpf-repro
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
