// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type L7ReceiverAcceptArgsT struct {
	_      structs.HostLayout
	Sockfd int32
	Pad    int32
	Addr   uint64
}

type L7ReceiverLocalAddrT struct {
	_         structs.HostLayout
	LocalAddr uint32
	LocalPort uint16
	Pad       uint16
}

type L7ReceiverReadArgsT struct {
	_   structs.HostLayout
	Fd  int32
	Pad int32
	Buf uint64
}

type L7ReceiverSocketInfoT struct {
	_          structs.HostLayout
	ClientAddr uint32
	ClientPort uint16
	Pad1       uint16
	LocalAddr  uint32
	LocalPort  uint16
	Pad2       uint16
	AcceptTime uint64
}

// LoadL7Receiver returns the embedded CollectionSpec for L7Receiver.
func LoadL7Receiver() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_L7ReceiverBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load L7Receiver: %w", err)
	}

	return spec, err
}

// LoadL7ReceiverObjects loads L7Receiver and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*L7ReceiverObjects
//	*L7ReceiverPrograms
//	*L7ReceiverMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadL7ReceiverObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadL7Receiver()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// L7ReceiverSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7ReceiverSpecs struct {
	L7ReceiverProgramSpecs
	L7ReceiverMapSpecs
	L7ReceiverVariableSpecs
}

// L7ReceiverProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7ReceiverProgramSpecs struct {
	KretprobeInetCskAccept *ebpf.ProgramSpec `ebpf:"kretprobe_inet_csk_accept"`
	SysEnterAccept4        *ebpf.ProgramSpec `ebpf:"sys_enter_accept4"`
	SysEnterClose          *ebpf.ProgramSpec `ebpf:"sys_enter_close"`
	SysEnterRead           *ebpf.ProgramSpec `ebpf:"sys_enter_read"`
	SysExitAccept4         *ebpf.ProgramSpec `ebpf:"sys_exit_accept4"`
	SysExitRead            *ebpf.ProgramSpec `ebpf:"sys_exit_read"`
}

// L7ReceiverMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7ReceiverMapSpecs struct {
	ActiveAcceptArgs *ebpf.MapSpec `ebpf:"active_accept_args"`
	ActiveReadArgs   *ebpf.MapSpec `ebpf:"active_read_args"`
	HttpEvents       *ebpf.MapSpec `ebpf:"http_events"`
	PendingLocalAddr *ebpf.MapSpec `ebpf:"pending_local_addr"`
	SocketInfoMap    *ebpf.MapSpec `ebpf:"socket_info_map"`
}

// L7ReceiverVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type L7ReceiverVariableSpecs struct {
}

// L7ReceiverObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadL7ReceiverObjects or ebpf.CollectionSpec.LoadAndAssign.
type L7ReceiverObjects struct {
	L7ReceiverPrograms
	L7ReceiverMaps
	L7ReceiverVariables
}

func (o *L7ReceiverObjects) Close() error {
	return _L7ReceiverClose(
		&o.L7ReceiverPrograms,
		&o.L7ReceiverMaps,
	)
}

// L7ReceiverMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadL7ReceiverObjects or ebpf.CollectionSpec.LoadAndAssign.
type L7ReceiverMaps struct {
	ActiveAcceptArgs *ebpf.Map `ebpf:"active_accept_args"`
	ActiveReadArgs   *ebpf.Map `ebpf:"active_read_args"`
	HttpEvents       *ebpf.Map `ebpf:"http_events"`
	PendingLocalAddr *ebpf.Map `ebpf:"pending_local_addr"`
	SocketInfoMap    *ebpf.Map `ebpf:"socket_info_map"`
}

func (m *L7ReceiverMaps) Close() error {
	return _L7ReceiverClose(
		m.ActiveAcceptArgs,
		m.ActiveReadArgs,
		m.HttpEvents,
		m.PendingLocalAddr,
		m.SocketInfoMap,
	)
}

// L7ReceiverVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadL7ReceiverObjects or ebpf.CollectionSpec.LoadAndAssign.
type L7ReceiverVariables struct {
}

// L7ReceiverPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadL7ReceiverObjects or ebpf.CollectionSpec.LoadAndAssign.
type L7ReceiverPrograms struct {
	KretprobeInetCskAccept *ebpf.Program `ebpf:"kretprobe_inet_csk_accept"`
	SysEnterAccept4        *ebpf.Program `ebpf:"sys_enter_accept4"`
	SysEnterClose          *ebpf.Program `ebpf:"sys_enter_close"`
	SysEnterRead           *ebpf.Program `ebpf:"sys_enter_read"`
	SysExitAccept4         *ebpf.Program `ebpf:"sys_exit_accept4"`
	SysExitRead            *ebpf.Program `ebpf:"sys_exit_read"`
}

func (p *L7ReceiverPrograms) Close() error {
	return _L7ReceiverClose(
		p.KretprobeInetCskAccept,
		p.SysEnterAccept4,
		p.SysEnterClose,
		p.SysEnterRead,
		p.SysExitAccept4,
		p.SysExitRead,
	)
}

func _L7ReceiverClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed l7receiver_bpfel.o
var _L7ReceiverBytes []byte
